# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuyList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManagerSwift', '~> 6.0.4'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.2.0'
  pod 'RealmSwift'
  pod 'GoogleSignIn'

  # Pods for BuyList

end
